### ISSUE TITLE
TH to statically turn a list into a vector?

### ISSUE THREAD

**Issue by Xandaros** [konn/sized-vector#6]
At the moment, you either have to manually construct the vector using Cons, or use fromList, which causes a runtime overhead and requires you to specify the length.
I know there is a function which infers the length, but often it is not able to do so.

I propose the addition of a Template Haskell function which allows the user to specify a Vector using the List-sugar, without needing to specify redundant information like the length.
(This is important. If you later want to add an element and forget to update the length, you will only notice at runtime that you have a problem. Not exactly ideal)

**Comment by konn** [comment]
Thank you for suggestion! I added `sized` and `sized'` TH macro to build sized vectors statically.
Usage:

```haskell
a = $(sized [1,2,3::Integer])

-- b = let a = "foo" in $(sized [a, "bar", "baz"])
b = let a = "foo" in $(sized' [[|a|], [|"bar"|], [|"baz"])
```
